### ISSUE TITLE
Unable to get the deployment details of the instances deployed through the grid-cli from the weblets' contract list.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tf-grid-cli#9]
## Describe the bug

Unable to get the deployment details of the instances deployed through the grid-cli from the weblets' contract list.

## To Reproduce

- Deploy anything from `grid-cli`
- Navigate to play.dev.grid.tf
- Load the same account used for the deployment.
- Navigate to the contracts list.
- Click on the `Show Details` button next to any of the contracts that belong to this deployment.
 
## Expected behavior

The deployment details of each contract should be returned successfully.

## Screenshots

![image](https://user-images.githubusercontent.com/101194226/226894655-af1527ac-fad0-4b05-a8c8-aa516c66fb72.png)

The error received when i click on the `Show Details` Button.

```
Deployment Error Error: Failed to send request to twinId 9 with command: zos.deployment.get, payload: {"contract_id":7739} due to invalid signature, discarding response
    at o.<anonymous> (client.js:22:23)
    at Generator.throw (<anonymous>)
    at s (client.js:5:57)
```

**Comment by mohamedamer453** [comment]
Closing since the issue was from another twin that i was using (probably related to pk since it wasn't working yet with the weblets).

Using another twin i was able to get the deployment details for a deployed vm

![image](https://user-images.githubusercontent.com/101194226/226966770-2c0876f2-00e8-484b-805a-e92e98573efe.png)

and its network

![image](https://user-images.githubusercontent.com/101194226/226966913-4851f334-2726-404f-8fcf-4d2bac75fb55.png)
